name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            forever stopall 
            cd /usr/ovijoy-api
            git add . 
            git commit -m "capture" 
            git config pull.rebase false 
            git pull origin ssh-main --force 
            git push 
            # git restore . 
            # git pull origin ssh-main --force 
            npm install 
            sudo forever start -c "sudo npm run forever" ./ 
            echo 'Deployment successful to bot live server....' 